//! Generates Rust source for the `aevo-sdk` crate from a [`UnifiedSpec`].
//!
//! Produces two files:
//! * `models.rs`  — type aliases, enums and structs for every schema.
//! * `endpoints.rs` — an `impl AevoClient` block with one async method per
//!   REST operation.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::names::{escape_ident, escape_method_name, to_pascal_case, to_snake_case};
use crate::openapi::{Operation, Schema};
use crate::parser::{EndpointOp, UnifiedSpec};

const HEADER: &str = "// @generated by aevo-codegen. Do not edit by hand.\n\
                      // Run `cargo run -p aevo-codegen` to regenerate.\n\n";

/// The two generated Rust source files.
pub struct GeneratedRest {
    pub models: String,
    pub endpoints: String,
}

/// Generate the REST models and endpoints source.
pub fn generate(spec: &UnifiedSpec) -> GeneratedRest {
    let mut ctx = TypeRegistry::new();

    // First, register top-level named schemas so they map to stable type names.
    for name in spec.schemas.keys() {
        ctx.register_named(name);
    }

    let endpoints = generate_endpoints(spec, &mut ctx);
    // Models must be generated last because endpoint generation creates inline
    // request/response structs that are appended to the model registry.
    let models = generate_models(spec, &mut ctx);

    GeneratedRest { models, endpoints }
}

/// Tracks how schema names map to Rust type names, and accumulates the
/// inline (anonymous) struct/enum definitions discovered while walking schemas.
struct TypeRegistry {
    /// schema name (snake_case) -> Rust type name (PascalCase).
    named: BTreeMap<String, String>,
    /// Generated inline type definitions, keyed by type name for de-dup.
    inline_defs: BTreeMap<String, String>,
    /// Track used type names to avoid collisions.
    used_names: std::collections::BTreeSet<String>,
}

impl TypeRegistry {
    fn new() -> Self {
        Self {
            named: BTreeMap::new(),
            inline_defs: BTreeMap::new(),
            used_names: std::collections::BTreeSet::new(),
        }
    }

    fn register_named(&mut self, schema_name: &str) -> String {
        if let Some(existing) = self.named.get(schema_name) {
            return existing.clone();
        }
        let base = to_pascal_case(schema_name);
        let unique = self.unique_name(&base);
        self.named.insert(schema_name.to_string(), unique.clone());
        unique
    }

    fn unique_name(&mut self, base: &str) -> String {
        let mut candidate = base.to_string();
        let mut i = 2;
        while self.used_names.contains(&candidate) {
            candidate = format!("{base}{i}");
            i += 1;
        }
        self.used_names.insert(candidate.clone());
        candidate
    }

    fn rust_type_for_named(&self, schema_name: &str) -> String {
        self.named
            .get(schema_name)
            .cloned()
            .unwrap_or_else(|| to_pascal_case(schema_name))
    }
}

// ----------------------------------------------------------------------------
// Models
// ----------------------------------------------------------------------------

fn generate_models(spec: &UnifiedSpec, ctx: &mut TypeRegistry) -> String {
    // Resolve all named schemas first (this may register further inline defs).
    let mut named_body = String::new();
    let schema_names: Vec<String> = spec.schemas.keys().cloned().collect();
    for name in &schema_names {
        let schema = spec.schemas.get(name).unwrap().clone();
        let type_name = ctx.rust_type_for_named(name);
        emit_named_schema(&mut named_body, &type_name, &schema, ctx);
    }

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(
        "#![allow(clippy::all)]\n\
         use serde::{Deserialize, Serialize};\n\n",
    );
    out.push_str(&named_body);

    // Inline structs/enums collected during model + endpoint generation.
    for def in ctx.inline_defs.values() {
        out.push_str(def);
        out.push('\n');
    }

    out
}

/// Emit a top-level named schema as a type alias, enum, or struct.
fn emit_named_schema(out: &mut String, type_name: &str, schema: &Schema, ctx: &mut TypeRegistry) {
    if let Some(doc) = &schema.description {
        emit_doc(out, doc, "");
    }

    // String enum.
    if !schema.enum_values.is_empty() && schema.ty.as_deref() == Some("string") {
        emit_string_enum(out, type_name, schema);
        return;
    }

    // Object with properties -> struct.
    if schema.ty.as_deref() == Some("object") && !schema.properties.is_empty() {
        emit_struct(out, type_name, schema, ctx);
        return;
    }

    // Everything else is a type alias to a primitive / Value / Vec.
    let inner = rust_type_alias_target(schema, ctx);
    let _ = writeln!(out, "pub type {type_name} = {inner};\n");
}

/// Resolve the aliased target type for a non-object, non-enum schema.
fn rust_type_alias_target(schema: &Schema, ctx: &mut TypeRegistry) -> String {
    match schema.ty.as_deref() {
        Some("string") => "String".to_string(),
        Some("integer") => "i64".to_string(),
        Some("number") => "f64".to_string(),
        Some("boolean") => "bool".to_string(),
        Some("array") => {
            let inner = schema
                .items
                .as_ref()
                .map(|it| register_schema_type(it, ctx, "Item"))
                .unwrap_or_else(|| "serde_json::Value".to_string());
            format!("Vec<{inner}>")
        }
        _ => "serde_json::Value".to_string(),
    }
}

/// Emit a string enum type.
fn emit_string_enum(out: &mut String, type_name: &str, schema: &Schema) {
    out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n");
    let _ = writeln!(out, "pub enum {type_name} {{");
    let mut seen = std::collections::BTreeSet::new();
    for value in &schema.enum_values {
        let Some(v) = value.as_str() else { continue };
        let mut variant = to_pascal_case(v);
        if variant.is_empty() {
            variant = "Empty".to_string();
        }
        // Avoid duplicate variant identifiers.
        let mut unique = variant.clone();
        let mut i = 2;
        while !seen.insert(unique.clone()) {
            unique = format!("{variant}{i}");
            i += 1;
        }
        let _ = writeln!(out, "    #[serde(rename = \"{v}\")]");
        let _ = writeln!(out, "    {unique},");
    }
    out.push_str("}\n\n");
}

/// Emit a struct for an object schema. Property field types resolve to named
/// types (for `$ref`) or inline types (registered into `ctx.inline_defs`).
fn emit_struct(out: &mut String, type_name: &str, schema: &Schema, ctx: &mut TypeRegistry) {
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    let _ = writeln!(out, "pub struct {type_name} {{");
    for (prop_name, prop_schema) in &schema.properties {
        let required = schema.required.iter().any(|r| r == prop_name);
        emit_field(out, type_name, prop_name, prop_schema, required, ctx);
    }
    out.push_str("}\n\n");
}

/// Emit a single struct field.
fn emit_field(
    out: &mut String,
    parent: &str,
    prop_name: &str,
    prop_schema: &Schema,
    required: bool,
    ctx: &mut TypeRegistry,
) {
    if let Some(doc) = &prop_schema.description {
        emit_doc(out, doc, "    ");
    }
    let field_ident = escape_ident(&to_snake_case(prop_name));
    let nested_hint = format!("{parent}{}", to_pascal_case(prop_name));
    let base_type = register_schema_type(prop_schema, ctx, &nested_hint);
    let ty = if required {
        base_type
    } else {
        format!("Option<{base_type}>")
    };

    let rust_bare = field_ident.trim_start_matches("r#");
    if prop_name != rust_bare {
        let _ = writeln!(out, "    #[serde(rename = \"{prop_name}\")]");
    }
    if !required {
        out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\", default)]\n");
    }
    let _ = writeln!(out, "    pub {field_ident}: {ty},");
}

// ----------------------------------------------------------------------------
// Endpoints
// ----------------------------------------------------------------------------

fn generate_endpoints(spec: &UnifiedSpec, ctx: &mut TypeRegistry) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(
        "#![allow(clippy::all)]\n\
         use crate::http::AevoClient;\n\
         use crate::error::Error;\n\
         use crate::models::*;\n\n\
         impl AevoClient {\n",
    );

    let mut used_method_names = std::collections::BTreeSet::new();
    for ep in &spec.operations {
        let method_src = generate_one_endpoint(ep, ctx, &mut used_method_names);
        out.push_str(&method_src);
    }

    out.push_str("}\n");
    out
}

fn generate_one_endpoint(
    ep: &EndpointOp,
    ctx: &mut TypeRegistry,
    used: &mut std::collections::BTreeSet<String>,
) -> String {
    let mut out = String::new();
    let op = &ep.op;

    // Method name: operationId if present, else <method>_<path>.
    let base_name = op
        .operation_id
        .clone()
        .unwrap_or_else(|| format!("{}_{}", ep.method, sanitize_path_for_name(&ep.path)));
    let mut method_name = escape_method_name(&base_name);
    let bare = method_name.trim_start_matches("r#").to_string();
    if used.contains(&bare) {
        let mut i = 2;
        loop {
            let candidate = format!("{bare}_{i}");
            if !used.contains(&candidate) {
                method_name = escape_ident(&candidate);
                break;
            }
            i += 1;
        }
    }
    used.insert(method_name.trim_start_matches("r#").to_string());

    // Doc comment.
    let summary = op
        .summary
        .clone()
        .or_else(|| op.description.clone())
        .unwrap_or_else(|| format!("{} {}", ep.method, ep.path));
    emit_doc(&mut out, &format!("`{} {}` — {}", ep.method, ep.path, summary), "    ");
    if let Some(desc) = &op.description {
        if Some(desc) != op.summary.as_ref() {
            emit_doc(&mut out, desc, "    ");
        }
    }

    // Parameters: path params (required, positional &str), then query params.
    let path_params: Vec<&crate::parser::ResolvedParam> =
        ep.params.iter().filter(|p| p.location == "path").collect();
    let query_params: Vec<&crate::parser::ResolvedParam> =
        ep.params.iter().filter(|p| p.location == "query").collect();

    // Request body type (if any JSON body).
    let body_type = request_body_type(op, ctx, &base_name);

    // Build the function signature.
    let mut args: Vec<String> = Vec::new();
    for p in &path_params {
        let ident = escape_ident(&to_snake_case(&p.name));
        args.push(format!("{ident}: &str"));
    }
    for p in &query_params {
        let ident = escape_ident(&to_snake_case(&p.name));
        let ty = param_rust_type(p);
        if p.required {
            args.push(format!("{ident}: {ty}"));
        } else {
            args.push(format!("{ident}: Option<{ty}>"));
        }
    }
    if let Some(bt) = &body_type {
        args.push(format!("body: &{bt}"));
    }

    // Return type = 200 response schema.
    let return_type = response_type(op, ctx, &base_name);

    let args_str = if args.is_empty() {
        String::new()
    } else {
        format!(", {}", args.join(", "))
    };

    let _ = writeln!(
        out,
        "    pub async fn {method_name}(&self{args_str}) -> Result<{return_type}, Error> {{"
    );

    // Build the runtime path, substituting `{param}` with formatted values.
    let path_expr = build_path_expr(&ep.path, &path_params);
    let _ = writeln!(out, "        let path = {path_expr};");

    // Query vec.
    if query_params.is_empty() {
        out.push_str("        let query: Option<&[(&str, String)]> = None;\n");
    } else {
        out.push_str("        let mut query_vec: Vec<(&str, String)> = Vec::new();\n");
        for p in &query_params {
            let ident = escape_ident(&to_snake_case(&p.name));
            let wire = &p.name;
            if p.required {
                let _ = writeln!(
                    out,
                    "        query_vec.push((\"{wire}\", {}.to_string()));",
                    ident
                );
            } else {
                let _ = writeln!(out, "        if let Some(v) = {ident} {{");
                let _ = writeln!(
                    out,
                    "            query_vec.push((\"{wire}\", v.to_string()));"
                );
                out.push_str("        }\n");
            }
        }
        out.push_str("        let query = Some(query_vec.as_slice());\n");
    }

    // Body.
    let body_expr = if body_type.is_some() {
        "Some(body)"
    } else {
        "None::<&()>"
    };

    let auth = !op.security.is_empty();
    let method_enum = format!("reqwest::Method::{}", ep.method);

    let _ = writeln!(
        out,
        "        self.send({method_enum}, &path, query, {body_expr}, {auth}).await",
    );
    out.push_str("    }\n\n");

    out
}

/// Determine the request body Rust type, registering an inline struct if the
/// body schema is an inline object. Returns `None` when there is no JSON body.
fn request_body_type(op: &Operation, ctx: &mut TypeRegistry, base_name: &str) -> Option<String> {
    let rb = op.request_body.as_ref()?;
    let media = rb.content.get("application/json")?;
    let schema = media.schema.as_ref()?;
    Some(register_schema_type(schema, ctx, &format!("{base_name}Body")))
}

/// Determine the success (200/201) response Rust type.
fn response_type(op: &Operation, ctx: &mut TypeRegistry, base_name: &str) -> String {
    for code in ["200", "201"] {
        if let Some(resp) = op.responses.get(code) {
            if let Some(media) = resp.content.get("application/json") {
                if let Some(schema) = &media.schema {
                    return register_schema_type(schema, ctx, &format!("{base_name}Response"));
                }
            }
            // Non-JSON (e.g. CSV) or empty body.
            return "serde_json::Value".to_string();
        }
    }
    "serde_json::Value".to_string()
}

/// Resolve a schema to a Rust type, registering inline objects/enums as named
/// types in the model registry so they get emitted in `models.rs`.
fn register_schema_type(schema: &Schema, ctx: &mut TypeRegistry, name_hint: &str) -> String {
    if let Some(ref_name) = schema.ref_name() {
        return ctx.rust_type_for_named(ref_name);
    }
    match schema.ty.as_deref() {
        Some("string") if schema.enum_values.is_empty() => "String".to_string(),
        Some("integer") => "i64".to_string(),
        Some("number") => "f64".to_string(),
        Some("boolean") => "bool".to_string(),
        Some("array") => {
            let inner = match &schema.items {
                Some(it) => register_schema_type(it, ctx, &format!("{name_hint}Item")),
                None => "serde_json::Value".to_string(),
            };
            format!("Vec<{inner}>")
        }
        Some("object") if !schema.properties.is_empty() => {
            register_inline_object(schema, ctx, name_hint)
        }
        _ if !schema.enum_values.is_empty() => register_inline_enum(schema, ctx, name_hint),
        _ => "serde_json::Value".to_string(),
    }
}

/// Register an inline object schema as a named struct in the model registry.
fn register_inline_object(schema: &Schema, ctx: &mut TypeRegistry, name_hint: &str) -> String {
    let title = schema.title.clone().unwrap_or_else(|| name_hint.to_string());
    let type_name = ctx.unique_name(&to_pascal_case(&title));

    // First resolve all field types (which may register further inline types),
    // then emit the struct definition.
    let mut body = String::new();
    if let Some(doc) = &schema.description {
        emit_doc(&mut body, doc, "");
    }
    body.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    let _ = writeln!(body, "pub struct {type_name} {{");
    for (prop_name, prop_schema) in &schema.properties {
        let required = schema.required.iter().any(|r| r == prop_name);
        if let Some(doc) = &prop_schema.description {
            emit_doc(&mut body, doc, "    ");
        }
        let field_ident = escape_ident(&to_snake_case(prop_name));
        let nested_hint = format!("{type_name}{}", to_pascal_case(prop_name));
        let base_type = register_schema_type(prop_schema, ctx, &nested_hint);
        let ty = if required {
            base_type
        } else {
            format!("Option<{base_type}>")
        };
        let rust_bare = field_ident.trim_start_matches("r#");
        if prop_name != rust_bare {
            let _ = writeln!(body, "    #[serde(rename = \"{prop_name}\")]");
        }
        if !required {
            body.push_str("    #[serde(skip_serializing_if = \"Option::is_none\", default)]\n");
        }
        let _ = writeln!(body, "    pub {field_ident}: {ty},");
    }
    body.push_str("}\n");

    ctx.inline_defs.insert(type_name.clone(), body);
    type_name
}

/// Register an inline string enum as a named enum in the model registry.
fn register_inline_enum(schema: &Schema, ctx: &mut TypeRegistry, name_hint: &str) -> String {
    let title = schema.title.clone().unwrap_or_else(|| name_hint.to_string());
    let type_name = ctx.unique_name(&to_pascal_case(&title));
    let mut body = String::new();
    emit_string_enum(&mut body, &type_name, schema);
    ctx.inline_defs.insert(type_name.clone(), body);
    type_name
}

/// Rust type for a query/path parameter value (always owned for query).
fn param_rust_type(p: &crate::parser::ResolvedParam) -> String {
    match p.schema.as_ref().and_then(|s| s.ty.as_deref()) {
        Some("integer") => "i64".to_string(),
        Some("number") => "f64".to_string(),
        Some("boolean") => "bool".to_string(),
        _ => "String".to_string(),
    }
}

/// Build the path expression, substituting path params with formatting.
fn build_path_expr(path: &str, path_params: &[&crate::parser::ResolvedParam]) -> String {
    if path_params.is_empty() {
        return format!("\"{path}\".to_string()");
    }
    // Convert `{order_id}` placeholders into `{}` and collect args.
    let mut fmt = String::new();
    let mut args: Vec<String> = Vec::new();
    let mut chars = path.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '{' {
            let mut name = String::new();
            for c2 in chars.by_ref() {
                if c2 == '}' {
                    break;
                }
                name.push(c2);
            }
            fmt.push_str("{}");
            args.push(escape_ident(&to_snake_case(&name)));
        } else {
            fmt.push(c);
        }
    }
    format!("format!(\"{fmt}\", {})", args.join(", "))
}

fn sanitize_path_for_name(path: &str) -> String {
    path.replace(['{', '}'], "").replace('/', "_")
}

// ----------------------------------------------------------------------------
// Shared helpers
// ----------------------------------------------------------------------------

/// Emit a `///` doc comment, escaping newlines and trimming noise.
fn emit_doc(out: &mut String, text: &str, indent: &str) {
    let cleaned = text.replace('\r', " ").replace('\n', " ");
    let cleaned = cleaned.trim();
    if cleaned.is_empty() {
        return;
    }
    // Wrap long docs to a single line each (keep it simple & deterministic).
    for line in textwrap_simple(cleaned, 100) {
        let _ = writeln!(out, "{indent}/// {line}");
    }
}

/// Extremely small word-wrap that never panics and is deterministic.
fn textwrap_simple(text: &str, width: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut current = String::new();
    for word in text.split_whitespace() {
        if current.is_empty() {
            current.push_str(word);
        } else if current.len() + 1 + word.len() > width {
            lines.push(std::mem::take(&mut current));
            current.push_str(word);
        } else {
            current.push(' ');
            current.push_str(word);
        }
    }
    if !current.is_empty() {
        lines.push(current);
    }
    lines
}
