//! WebSocket client generation.
//!
//! The WebSocket documentation pages are human-formatted tables rather than
//! OpenAPI, but each one embeds fenced ```json examples for the subscribe
//! REQUEST and the message RESPONSE. We parse those examples, infer Rust
//! structs from the RESPONSE shape, and emit:
//!
//! * one message struct per channel (plus nested structs), and
//! * a `Channel` enum enumerating the known channels.
//!
//! The hand-written `WsClient` runtime (in `aevo-sdk/src/ws/mod.rs`) consumes
//! these generated types.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use serde_json::Value;

use crate::downloader::Doc;
use crate::names::{escape_ident, to_pascal_case, to_snake_case};

const HEADER: &str = "// @generated by aevo-codegen. Do not edit by hand.\n\
                      // Run `cargo run -p aevo-codegen` to regenerate.\n\n";

/// A parsed WebSocket channel from a documentation page.
#[derive(Debug, Clone)]
struct WsChannel {
    /// Logical channel name, e.g. `fills`, `orderbook`, `book-ticker`.
    name: String,
    /// Source doc relative path.
    source: String,
    /// The RESPONSE example payload, if found.
    response: Option<Value>,
    /// The REQUEST example payload, if found.
    request: Option<Value>,
}

/// Extract every fenced ```json block from a markdown string.
fn extract_json_blocks(md: &str) -> Vec<String> {
    let mut blocks = Vec::new();
    let mut rest = md;
    while let Some(start) = rest.find("```json") {
        let after = &rest[start + "```json".len()..];
        if let Some(end) = after.find("```") {
            blocks.push(after[..end].trim().to_string());
            rest = &after[end + 3..];
        } else {
            break;
        }
    }
    blocks
}

/// Detect WebSocket doc pages and parse their request/response examples.
fn parse_ws_docs(docs: &[Doc]) -> Vec<WsChannel> {
    let mut channels = Vec::new();
    let mut docs_sorted: Vec<&Doc> = docs.iter().collect();
    docs_sorted.sort_by(|a, b| a.rel_path.cmp(&b.rel_path));

    for doc in docs_sorted {
        // A WS page advertises the websocket endpoint.
        if !doc.contents.contains("wss://ws.aevo.xyz") {
            continue;
        }
        let blocks = extract_json_blocks(&doc.contents);
        if blocks.is_empty() {
            continue;
        }

        let mut request: Option<Value> = None;
        let mut response: Option<Value> = None;
        for block in &blocks {
            let Ok(val) = serde_json::from_str::<Value>(block) else {
                continue;
            };
            let is_request = val.get("op").is_some() || val.get("data").map(|d| d.is_array()).unwrap_or(false);
            if is_request && request.is_none() {
                request = Some(val);
            } else if response.is_none() {
                response = Some(val);
            }
        }

        let name = channel_name(&doc.rel_path, request.as_ref(), response.as_ref());
        channels.push(WsChannel {
            name,
            source: doc.rel_path.clone(),
            response,
            request,
        });
    }

    // Deterministic order, de-duplicate by channel name.
    channels.sort_by(|a, b| a.name.cmp(&b.name));
    channels.dedup_by(|a, b| a.name == b.name);
    channels
}

/// Derive a channel name from the response `channel` field, the request `data`
/// array, or the file name as a fallback.
fn channel_name(rel_path: &str, request: Option<&Value>, response: Option<&Value>) -> String {
    if let Some(resp) = response {
        if let Some(ch) = resp.get("channel").and_then(|c| c.as_str()) {
            return normalize_channel(ch);
        }
    }
    if let Some(req) = request {
        if let Some(arr) = req.get("data").and_then(|d| d.as_array()) {
            if let Some(first) = arr.first().and_then(|v| v.as_str()) {
                return normalize_channel(first);
            }
        }
    }
    // Fallback: derive from filename, stripping the subscribe prefix.
    let file = rel_path.rsplit('/').next().unwrap_or(rel_path);
    let stem = file.trim_end_matches(".md");
    let stem = stem
        .trim_start_matches("subscribe-")
        .trim_start_matches("subcribe-");
    normalize_channel(stem)
}

/// Channels may be parameterized like `orderbook:ETH-PERP`; keep the base name.
fn normalize_channel(ch: &str) -> String {
    ch.split(':').next().unwrap_or(ch).trim().to_string()
}

/// Generate `ws/messages.rs` source from the parsed WS docs.
pub fn generate(docs: &[Doc]) -> String {
    let channels = parse_ws_docs(docs);

    let mut nested: BTreeMap<String, String> = BTreeMap::new();
    let mut used: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    let mut top_level = String::new();
    let mut channel_variants: Vec<(String, String)> = Vec::new();

    for ch in &channels {
        let type_base = format!("{}Message", to_pascal_case(&ch.name));
        let variant = to_pascal_case(&ch.name);
        channel_variants.push((variant, ch.name.clone()));

        let Some(resp) = &ch.response else {
            // No response example: still record the channel, emit a Value alias.
            let alias = unique(&type_base, &mut used);
            let _ = writeln!(
                top_level,
                "/// Message payload for the `{}` channel (source: {}).\n\
                 /// No response example was available; falls back to raw JSON.\n\
                 pub type {alias} = serde_json::Value;\n",
                ch.name, ch.source
            );
            continue;
        };

        let type_name = unique(&type_base, &mut used);
        let _ = writeln!(
            top_level,
            "/// Message payload for the `{}` channel (source: {}).",
            ch.name, ch.source
        );
        let def = infer_struct(&type_name, resp, &mut nested, &mut used);
        top_level.push_str(&def);
        top_level.push('\n');
    }

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(
        "#![allow(clippy::all)]\n\
         use serde::{Deserialize, Serialize};\n\n",
    );

    // Channel enum.
    out.push_str("/// Known Aevo WebSocket channels (base names; some accept parameters).\n");
    out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
    out.push_str("pub enum Channel {\n");
    for (variant, _) in &channel_variants {
        let _ = writeln!(out, "    {variant},");
    }
    out.push_str("    /// Any channel not known at generation time.\n    Other(String),\n}\n\n");

    out.push_str("impl Channel {\n");
    out.push_str("    /// The wire name for this channel's base.\n");
    out.push_str("    pub fn as_str(&self) -> &str {\n        match self {\n");
    for (variant, name) in &channel_variants {
        let _ = writeln!(out, "            Channel::{variant} => \"{name}\",");
    }
    out.push_str("            Channel::Other(s) => s.as_str(),\n        }\n    }\n}\n\n");

    // Message structs.
    out.push_str(&top_level);
    for def in nested.values() {
        out.push_str(def);
        out.push('\n');
    }

    out
}

fn unique(base: &str, used: &mut std::collections::BTreeSet<String>) -> String {
    let mut candidate = base.to_string();
    let mut i = 2;
    while used.contains(&candidate) {
        candidate = format!("{base}{i}");
        i += 1;
    }
    used.insert(candidate.clone());
    candidate
}

/// Infer a struct definition from a JSON object value. Nested objects are
/// registered into `nested`. Returns the struct source for `type_name`.
fn infer_struct(
    type_name: &str,
    value: &Value,
    nested: &mut BTreeMap<String, String>,
    used: &mut std::collections::BTreeSet<String>,
) -> String {
    let mut body = String::new();
    body.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    let _ = writeln!(body, "pub struct {type_name} {{");

    if let Some(map) = value.as_object() {
        for (key, val) in map {
            let field_ident = escape_ident(&to_snake_case(key));
            let hint = format!("{type_name}{}", to_pascal_case(key));
            let ty = infer_type(val, &hint, nested, used);
            let rust_bare = field_ident.trim_start_matches("r#");
            if key != rust_bare {
                let _ = writeln!(body, "    #[serde(rename = \"{key}\")]");
            }
            let _ = writeln!(body, "    pub {field_ident}: {ty},");
        }
    }
    body.push_str("}\n");
    body
}

/// Infer the Rust type for a JSON value, registering nested structs as needed.
fn infer_type(
    value: &Value,
    name_hint: &str,
    nested: &mut BTreeMap<String, String>,
    used: &mut std::collections::BTreeSet<String>,
) -> String {
    match value {
        Value::Null => "Option<serde_json::Value>".to_string(),
        Value::Bool(_) => "bool".to_string(),
        Value::Number(n) => {
            if n.is_i64() || n.is_u64() {
                "i64".to_string()
            } else {
                "f64".to_string()
            }
        }
        Value::String(_) => "String".to_string(),
        Value::Array(items) => {
            let inner = match items.first() {
                Some(first) => infer_type(first, &format!("{name_hint}Item"), nested, used),
                None => "serde_json::Value".to_string(),
            };
            format!("Vec<{inner}>")
        }
        Value::Object(_) => {
            let type_name = unique(&to_pascal_case(name_hint), used);
            let def = infer_struct(&type_name, value, nested, used);
            nested.insert(type_name.clone(), def);
            type_name
        }
    }
}
