// @generated by aevo-codegen. Do not edit by hand.
// Run `cargo run -p aevo-codegen` to regenerate.

#![allow(clippy::all)]

/// Known Aevo WebSocket channels (regenerated from the docs).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Channel {
    /// Any channel not known at generation time.
    Other(String),
}

impl Channel {
    /// The wire name for this channel's base.
    pub fn as_str(&self) -> &str {
        match self {
            Channel::Other(s) => s.as_str(),
        }
    }
}
