// @generated by aevo-codegen. Do not edit by hand.
// Run `cargo run -p aevo-codegen` to regenerate.

#![allow(clippy::all)]
use crate::http::AevoClient;
use crate::error::Error;
use crate::models::*;

impl AevoClient {
    /// `GET /account` — GET /account
    /// Returns the account's information including API keys, signing keys and positions.
    pub async fn get_account(&self) -> Result<GetAccount200Response, Error> {
        let path = "/account".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /account/accumulated-fundings` — GET /account/accumulated-fundings
    /// Get the accumulated funding for your account's positions.
    pub async fn get_account_accumulated_fundings(&self) -> Result<GetAccountAccumulatedFundings200Response, Error> {
        let path = "/account/accumulated-fundings".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /account/cancel-on-disconnect` — GET /account/cancel-on-disconnect
    /// Check the Cancel on Disconnect (CoD) setting for your account.
    pub async fn get_account_cancel_on_disconnect(&self) -> Result<GetAccountCancelOnDisconnect200Response, Error> {
        let path = "/account/cancel-on-disconnect".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `POST /account/cancel-on-disconnect` — POST /account/cancel-on-disconnect
    /// Enables or disables the Cancel on Disconnect (CoD) setting for your account. When CoD is enabled,
    /// when a websocket connection is closed, all orders placed via that connection will be cancelled.
    pub async fn post_account_cancel_on_disconnect(&self, body: &PostAccountCancelOnDisconnectPayload) -> Result<PostAccountCancelOnDisconnect200Response, Error> {
        let path = "/account/cancel-on-disconnect".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `GET /account/email-address` — GET /account/email-address
    /// Check the Email Address for your account.
    pub async fn get_account_email_address(&self) -> Result<GetAccountEmailAddress200Response, Error> {
        let path = "/account/email-address".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /account/email-address` — POST /account/email-address
    /// Sets up an email address for a user.
    pub async fn post_account_email_address(&self, body: &PostAccountEmailAddressPayload) -> Result<PostAccountEmailAddress200Response, Error> {
        let path = "/account/email-address".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `POST /account/email-preference` — POST /account/email-preference
    /// Sets up email preference for a user.
    pub async fn post_account_email_preference(&self, body: &PostAccountEmailPreferencePayload) -> Result<PostAccountEmailPreference200Response, Error> {
        let path = "/account/email-preference".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `GET /account/email-preferences` — GET /account/email-preferences
    /// Check the email preferences for your account.
    pub async fn get_account_email_preferences(&self) -> Result<GetAccountEmailPreferences200Response, Error> {
        let path = "/account/email-preferences".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /account/email-verified` — GET /account/email-verified
    /// Check if an account's email is verified.
    pub async fn get_account_email_verified(&self) -> Result<GetAccountEmailVerified200Response, Error> {
        let path = "/account/email-verified".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /account/email-verified` — POST /account/email-verified
    /// Verify an account's email.
    pub async fn post_account_email_verified(&self, body: &PostAccountEmailVerifiedPayload) -> Result<PostAccountEmailVerified200Response, Error> {
        let path = "/account/email-verified".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), false).await
    }

    /// `POST /account/leverage` — POST /account/leverage
    /// Set the leverage of an instrument for your account.
    pub async fn post_account_leverage(&self, body: &PostAccountLeveragePayload) -> Result<PostAccountLeverage200Response, Error> {
        let path = "/account/leverage".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `POST /account/margin-type` — POST /account/margin-type
    /// Update margin for your account's positions.
    pub async fn post_account_margin_type(&self, body: &PostAccountMarginTypePayload) -> Result<PostAccountMarginType200Response, Error> {
        let path = "/account/margin-type".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `POST /account/network-address` — POST /account/network-address
    /// Set a non-eth network's address to the account
    pub async fn post_account_network_address(&self, body: &PostAccountNetworkAddressPayload) -> Result<PostAccountNetworkAddress200Response, Error> {
        let path = "/account/network-address".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `POST /account/portfolio-margin` — POST /account/portfolio-margin
    /// Enables or disables the portfolio margin on your acccount.
    pub async fn post_account_portfolio_margin(&self, body: &PostAccountPortfolioMarginPayload) -> Result<PostAccountPortfolioMargin200Response, Error> {
        let path = "/account/portfolio-margin".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `GET /account/stats` — GET /account/stats
    /// Returns the account's statistics of volume and pnl
    pub async fn get_account_stats(&self, start_time: Option<i64>, end_time: Option<i64>, asset: Option<String>, campaign_name: Option<String>) -> Result<GetAccountStats200Response, Error> {
        let path = "/account/stats".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = start_time {
            query_vec.push(("start_time", v.to_string()));
        }
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = asset {
            query_vec.push(("asset", v.to_string()));
        }
        if let Some(v) = campaign_name {
            query_vec.push(("campaign_name", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /account/trades/csv` — GET /account/trades/csv
    /// Returns account's trade history in CSV format
    pub async fn get_account_trades_csv(&self, trade_types: String, start_time: i64, end_time: Option<i64>) -> Result<serde_json::Value, Error> {
        let path = "/account/trades/csv".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("trade_types", trade_types.to_string()));
        query_vec.push(("start_time", start_time.to_string()));
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /account/transactions/csv` — GET /account/transactions/csv
    /// Returns account's transactions history in CSV format
    pub async fn get_account_transactions_csv(&self, start_time: i64, end_time: Option<i64>) -> Result<serde_json::Value, Error> {
        let path = "/account/transactions/csv".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("start_time", start_time.to_string()));
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /account/unsubscribe` — POST /account/unsubscribe
    /// Unsubscribe from all email preferences
    pub async fn post_account_unsubscribe(&self, body: &PostAccountUnsubscribePayload) -> Result<PostAccountUnsubscribe200Response, Error> {
        let path = "/account/unsubscribe".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), false).await
    }

    /// `POST /account/update-margin` — POST /account/update-margin
    /// Update margin for your account's positions.
    pub async fn post_account_update_margin(&self, body: &PostAccountUpdateMarginPayload) -> Result<PostAccountUpdateMargin200Response, Error> {
        let path = "/account/update-margin".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `POST /account/username` — POST /account/username
    /// Sets the username for your account.
    pub async fn post_account_username(&self, body: &PostAccountUsernamePayload) -> Result<PostAccountUsername200Response, Error> {
        let path = "/account/username".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `GET /account/weekly-volume` — GET /account/weekly-volume
    /// Returns the account's weekly trading volume and multiplier tier for LP NFT distribution.
    pub async fn get_account_weekly_volume(&self) -> Result<GetAccountWeeklyVolume200Response, Error> {
        let path = "/account/weekly-volume".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /airdrop-incentivized-assets` — GET /airdrop-incentivized-assets
    /// Returns a list of airdrop incentivized assets
    pub async fn get_airdrop_incentivized_assets(&self) -> Result<GetAirdropIncentivizedAssets200Response, Error> {
        let path = "/airdrop-incentivized-assets".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `DELETE /api-key` — DELETE /api-key
    /// Removes the account's API key. This logs out the account.
    pub async fn delete_api_key(&self, body: &DeleteApiKeyPayload) -> Result<DeleteApiKey200Response, Error> {
        let path = "/api-key".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::DELETE, &path, query, Some(body), true).await
    }

    /// `GET /api-key` — GET /api-key
    /// Returns the API key information.
    pub async fn get_api_key(&self, api_key: String, timestamp: String, signature: String) -> Result<GetApiKey200Response, Error> {
        let path = "/api-key".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("api_key", api_key.to_string()));
        query_vec.push(("timestamp", timestamp.to_string()));
        query_vec.push(("signature", signature.to_string()));
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `POST /api-key` — POST /api-key
    /// Creates a new API key.
    pub async fn post_api_key(&self, body: &PostApiKeyPayload) -> Result<PostApiKey200Response, Error> {
        let path = "/api-key".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `GET /assets` — GET /assets
    /// Returns the list of active underlying assets.
    pub async fn get_assets(&self) -> Result<Vec<AssetResponse>, Error> {
        let path = "/assets".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /auth` — GET /auth
    /// Returns true if the given headers has valid authentication
    pub async fn get_auth(&self) -> Result<GetAuth200Response, Error> {
        let path = "/auth".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /batch-orders` — POST /batch-orders
    /// Creates a deterministic batch of GTC limit orders. All legs must share account, instrument, side,
    /// post_only, and reduce_only.
    pub async fn post_batch_orders(&self, body: &PostBatchOrdersPayload) -> Result<PostBatchOrders200Response, Error> {
        let path = "/batch-orders".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `POST /campaign-sign-up` — POST /campaign-sign-up
    /// Sign up for a campaign
    pub async fn post_campaign_sign_up(&self, body: &PostCampaignSignUpPayload) -> Result<PostCampaignSignUp200Response, Error> {
        let path = "/campaign-sign-up".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `GET /check-referral` — GET /check-referral
    /// Check if user can be referred.
    pub async fn get_check_referral(&self, account: String, referral_code: String) -> Result<GetCheckReferral200Response, Error> {
        let path = "/check-referral".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("account", account.to_string()));
        query_vec.push(("referral_code", referral_code.to_string()));
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `POST /claim-referral-rewards` — POST /claim-referral-rewards
    /// User claims referral rewards
    pub async fn post_claim_referral_rewards(&self) -> Result<PostClaimReferralRewards200Response, Error> {
        let path = "/claim-referral-rewards".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, None::<&()>, true).await
    }

    /// `POST /claim-trade-fees` — POST /claim-trade-fees
    /// User claims trade fees rewards
    pub async fn post_claim_trade_fees(&self) -> Result<PostClaimTradeFees200Response, Error> {
        let path = "/claim-trade-fees".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, None::<&()>, true).await
    }

    /// `GET /coingecko-statistics` — GET /coingecko-statistics
    /// Returns the perpetual statistics of all assets specifically for
    /// https://www.coingecko.com/en/exchanges/aevo
    pub async fn get_coingecko_statistics(&self) -> Result<Vec<GetCoingeckoStatistics200Response>, Error> {
        let path = "/coingecko-statistics".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /emissions` — GET /emissions
    /// Returns the farm + staking emissions
    pub async fn get_emissions(&self) -> Result<Vec<GetEmissions200Response>, Error> {
        let path = "/emissions".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /expiries` — GET /expiries
    /// Returns the expiry timestamps of derivatives of the given asset.
    pub async fn get_expiries(&self, asset: String) -> Result<Vec<ExpiryResponse>, Error> {
        let path = "/expiries".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("asset", asset.to_string()));
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /farm-boost` — GET /farm-boost
    /// Returns current farm boost, avg farm boost, and boosted volume
    pub async fn get_farm_boost(&self) -> Result<GetFarmBoost200Response, Error> {
        let path = "/farm-boost".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /farm-boost` — POST /farm-boost
    /// Sets random farm boost
    pub async fn post_farm_boost(&self) -> Result<PostFarmBoost200Response, Error> {
        let path = "/farm-boost".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, None::<&()>, true).await
    }

    /// `GET /funding` — GET /funding
    /// Returns the current funding rate for the instrument.
    pub async fn get_funding(&self, instrument_name: String) -> Result<GetFunding200Response, Error> {
        let path = "/funding".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("instrument_name", instrument_name.to_string()));
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /funding-history` — GET /funding-history
    /// Returns the funding rate history for the instrument.
    pub async fn get_funding_history(&self, instrument_name: Option<String>, start_time: Option<i64>, end_time: Option<i64>, limit: Option<i64>) -> Result<GetFundingHistory200Response, Error> {
        let path = "/funding-history".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = instrument_name {
            query_vec.push(("instrument_name", v.to_string()));
        }
        if let Some(v) = start_time {
            query_vec.push(("start_time", v.to_string()));
        }
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /index` — GET /index
    /// Returns the current index price of the given asset.
    pub async fn get_index(&self, asset: String) -> Result<GetIndex200Response, Error> {
        let path = "/index".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("asset", asset.to_string()));
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /index-history` — GET /index-history
    /// Returns the historical index price for a given asset.
    pub async fn get_index_history(&self, asset: String, resolution: Option<i64>, start_time: Option<i64>, end_time: Option<i64>, limit: Option<i64>) -> Result<GetIndexHistory200Response, Error> {
        let path = "/index-history".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("asset", asset.to_string()));
        if let Some(v) = resolution {
            query_vec.push(("resolution", v.to_string()));
        }
        if let Some(v) = start_time {
            query_vec.push(("start_time", v.to_string()));
        }
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /instrument/{instrument_name}` — GET /instrument/{instrument_name}
    /// Returns the instrument information for the given instrument.
    pub async fn get_instrument_instrument_name(&self, instrument_name: &str) -> Result<GetInstrumentInstrumentName200Response, Error> {
        let path = format!("/instrument/{}", instrument_name);
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /instrument/{instrument_name}/trade-history` — GET
    /// /instrument/{instrument_name}/trade-history
    /// Returns the trade history for the given instrument.
    pub async fn get_instrument_instrument_name_trade_history(&self, instrument_name: &str, start_time: Option<i64>, end_time: Option<i64>) -> Result<GetInstrumentInstrumentNameTradeHistory200Response, Error> {
        let path = format!("/instrument/{}/trade-history", instrument_name);
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = start_time {
            query_vec.push(("start_time", v.to_string()));
        }
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /leaderboard/campaign` — GET /leaderboard/campaign
    /// Returns the leaderboard for a campaign by pnl in descending order
    pub async fn get_leaderboard_campaign(&self, username: String, limit: Option<i64>, start_time: i64, end_time: i64) -> Result<GetLeaderboardCampaign200Response, Error> {
        let path = "/leaderboard/campaign".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("username", username.to_string()));
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        query_vec.push(("start_time", start_time.to_string()));
        query_vec.push(("end_time", end_time.to_string()));
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /mark-history` — GET /mark-history
    /// Returns the historical mark prices for a given instrument.
    pub async fn get_mark_history(&self, instrument_name: String, resolution: Option<i64>, limit: Option<i64>, start_time: Option<i64>, end_time: Option<i64>) -> Result<GetMarkHistory200Response, Error> {
        let path = "/mark-history".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("instrument_name", instrument_name.to_string()));
        if let Some(v) = resolution {
            query_vec.push(("resolution", v.to_string()));
        }
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        if let Some(v) = start_time {
            query_vec.push(("start_time", v.to_string()));
        }
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /markets` — GET /markets
    /// Returns a list of instruments. If `asset` is not specified, the response will include all listed
    /// instruments.
    pub async fn get_markets(&self, asset: Option<String>, instrument_type: Option<String>) -> Result<Vec<GetMarkets200Response>, Error> {
        let path = "/markets".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = asset {
            query_vec.push(("asset", v.to_string()));
        }
        if let Some(v) = instrument_type {
            query_vec.push(("instrument_type", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /mmp` — GET /mmp
    /// Get market maker protection (MMP) setting.
    pub async fn get_mmp(&self, asset: String) -> Result<GetMmp200Response, Error> {
        let path = "/mmp".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("asset", asset.to_string()));
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /mmp` — POST /mmp
    /// Sets market maker protection (MMP) settings.
    pub async fn post_mmp(&self, body: &PostMmpPayload) -> Result<PostMmp200Response, Error> {
        let path = "/mmp".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `GET /options-history` — GET /options-history
    /// Returns the trade history for group of instrument.
    pub async fn get_options_history(&self, asset: String, start_time: Option<i64>, end_time: Option<i64>, option_type: Option<String>, offset: Option<i64>, limit: Option<i64>) -> Result<Vec<GetOptionsHistory200Response>, Error> {
        let path = "/options-history".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("asset", asset.to_string()));
        if let Some(v) = start_time {
            query_vec.push(("start_time", v.to_string()));
        }
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = option_type {
            query_vec.push(("option_type", v.to_string()));
        }
        if let Some(v) = offset {
            query_vec.push(("offset", v.to_string()));
        }
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /order-history` — GET /order-history
    /// Returns order history for the account.
    pub async fn get_order_history(&self, start_time: i64, end_time: Option<i64>, limit: Option<i64>, offset: Option<i64>) -> Result<GetOrderHistory200Response, Error> {
        let path = "/order-history".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("start_time", start_time.to_string()));
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        if let Some(v) = offset {
            query_vec.push(("offset", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /order-history/stops` — GET /order-history/stops
    /// Returns stop order history for the account.
    pub async fn get_order_history_stops(&self, start_time: i64, end_time: Option<i64>, limit: Option<i64>, offset: Option<i64>) -> Result<GetOrderHistoryStops200Response, Error> {
        let path = "/order-history/stops".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("start_time", start_time.to_string()));
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        if let Some(v) = offset {
            query_vec.push(("offset", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /orderbook` — GET /orderbook
    /// Returns the orderbook for a given symbol.
    pub async fn get_orderbook(&self, instrument_name: String) -> Result<GetOrderbook200Response, Error> {
        let path = "/orderbook".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("instrument_name", instrument_name.to_string()));
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /orders` — GET /orders
    /// Returns all account's orders.
    pub async fn get_orders(&self) -> Result<Vec<GetOrders200Response>, Error> {
        let path = "/orders".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /orders` — POST /orders
    /// Creates a new order.
    pub async fn post_orders(&self, body: &PostOrdersPayload) -> Result<PostOrders200Response, Error> {
        let path = "/orders".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `DELETE /orders-all` — DELETE /orders-all
    /// Cancel all orders. Optionally, you can specify an asset and instrument type to cancel only orders
    /// for that asset/instrument type.
    pub async fn delete_orders_all(&self, body: &DeleteOrdersAllPayload) -> Result<DeleteOrdersAll200Response, Error> {
        let path = "/orders-all".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::DELETE, &path, query, Some(body), true).await
    }

    /// `DELETE /orders/{order_id}` — DELETE /orders/{order_id}
    /// Cancels an order.
    pub async fn delete_orders_order_id(&self, order_id: &str) -> Result<DeleteOrdersOrderId200Response, Error> {
        let path = format!("/orders/{}", order_id);
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::DELETE, &path, query, None::<&()>, true).await
    }

    /// `GET /orders/{order_id}` — GET /orders/{order_id}
    /// Returns the order details.
    pub async fn get_orders_order_id(&self, order_id: &str) -> Result<GetOrdersOrderId200Response, Error> {
        let path = format!("/orders/{}", order_id);
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /orders/{order_id}` — POST /orders/{order_id}
    /// Edits an existing order.
    pub async fn post_orders_order_id(&self, order_id: &str, body: &PostOrdersOrderIdPayload) -> Result<PostOrdersOrderId200Response, Error> {
        let path = format!("/orders/{}", order_id);
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `GET /otc/account` — GET /otc/account
    /// Returns the account's otc details
    pub async fn get_otc_account(&self) -> Result<GetOtcAccount200Response, Error> {
        let path = "/otc/account".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /otc/create-request` — POST /otc/create-request
    /// Create a new otc request
    pub async fn post_otc_create_request(&self, body: &PostOtcCreateRequestPayload) -> Result<PostOtcCreateRequest200Response, Error> {
        let path = "/otc/create-request".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `POST /otc/unwind` — POST /otc/unwind
    /// Unwind an otc position
    pub async fn post_otc_unwind(&self, body: &PostOtcUnwindPayload) -> Result<PostOtcUnwind200Response, Error> {
        let path = "/otc/unwind".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `GET /portfolio` — GET /portfolio
    /// Returns the overall portfolio details of the account.
    pub async fn get_portfolio(&self) -> Result<GetPortfolio200Response, Error> {
        let path = "/portfolio".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /positions` — GET /positions
    /// Returns the account's positions
    pub async fn get_positions(&self) -> Result<GetPositions200Response, Error> {
        let path = "/positions".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /proof-data` — GET /proof-data
    /// Returns account's proof data
    pub async fn get_proof_data(&self, json_name: String) -> Result<GetProofData200Response, Error> {
        let path = "/proof-data".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("json_name", json_name.to_string()));
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /proofs-data` — GET /proofs-data
    /// Returns account's proof data
    pub async fn get_proofs_data(&self, assets: String) -> Result<GetProofsData200Response, Error> {
        let path = "/proofs-data".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("assets", assets.to_string()));
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `DELETE /quotes` — DELETE /quotes
    /// Cancel multiple quotes.
    pub async fn delete_quotes(&self, quote_ids: Option<String>, block_id: Option<String>) -> Result<DeleteQuotes200Response, Error> {
        let path = "/quotes".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = quote_ids {
            query_vec.push(("quote_ids", v.to_string()));
        }
        if let Some(v) = block_id {
            query_vec.push(("block_id", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::DELETE, &path, query, None::<&()>, true).await
    }

    /// `GET /quotes` — GET /quotes
    /// Returns all account's quotes.
    pub async fn get_quotes(&self) -> Result<GetQuotes200Response, Error> {
        let path = "/quotes".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /quotes` — POST /quotes
    /// Creates a new quote.
    pub async fn post_quotes(&self, body: &PostQuotesPayload) -> Result<PostQuotes200Response, Error> {
        let path = "/quotes".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `POST /quotes/preview` — POST /quotes/preview
    /// Simulate a new quote.
    pub async fn post_quotes_preview(&self, body: &PostQuotesPreviewPayload) -> Result<PostQuotesPreview200Response, Error> {
        let path = "/quotes/preview".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `DELETE /quotes/{quote_id}` — DELETE /quotes/{quote_id}
    /// Cancels an quote.
    pub async fn delete_quotes_quote_id(&self, quote_id: &str) -> Result<DeleteQuotesQuoteId200Response, Error> {
        let path = format!("/quotes/{}", quote_id);
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::DELETE, &path, query, None::<&()>, true).await
    }

    /// `PUT /quotes/{quote_id}` — PUT /quotes/{quote_id}
    /// Edits an existing quote.
    pub async fn put_quotes_quote_id(&self, quote_id: &str, body: &PutQuotesQuoteIdPayload) -> Result<PutQuotesQuoteId200Response, Error> {
        let path = format!("/quotes/{}", quote_id);
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::PUT, &path, query, Some(body), true).await
    }

    /// `GET /referral-history` — GET /referral-history
    /// Return the account's referral history.
    pub async fn get_referral_history(&self, limit: Option<i64>, offset: Option<i64>) -> Result<GetReferralHistory200Response, Error> {
        let path = "/referral-history".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        if let Some(v) = offset {
            query_vec.push(("offset", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /referral-rewards-history` — GET /referral-rewards-history
    /// Return the account's referral rewards history.
    pub async fn get_referral_rewards_history(&self, limit: Option<i64>, offset: Option<i64>) -> Result<GetReferralRewardsHistory200Response, Error> {
        let path = "/referral-rewards-history".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        if let Some(v) = offset {
            query_vec.push(("offset", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /referral-statistics` — GET /referral-statistics
    /// Return the account's referral statistics.
    pub async fn get_referral_statistics(&self, start_time: Option<i64>) -> Result<GetReferralStatistics200Response, Error> {
        let path = "/referral-statistics".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = start_time {
            query_vec.push(("start_time", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /register` — POST /register
    /// Registers a new account.
    pub async fn post_register(&self, body: &PostRegisterPayload) -> Result<PostRegister200Response, Error> {
        let path = "/register".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), false).await
    }

    /// `POST /reset-mmp` — POST /reset-mmp
    /// Reset market maker protection (MMP).
    pub async fn post_reset_mmp(&self, body: &PostResetMmpPayload) -> Result<PostResetMmp200Response, Error> {
        let path = "/reset-mmp".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `DELETE /rfqs` — DELETE /rfqs
    /// Cancel all blocks.
    pub async fn delete_rfqs(&self) -> Result<DeleteRfqs200Response, Error> {
        let path = "/rfqs".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::DELETE, &path, query, None::<&()>, true).await
    }

    /// `GET /rfqs` — GET /rfqs
    /// Get RFQ blocks open for trading.
    pub async fn get_rfqs(&self, role: Option<String>) -> Result<GetRfqs200Response, Error> {
        let path = "/rfqs".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = role {
            query_vec.push(("role", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /rfqs` — POST /rfqs
    /// Create a new RFQ block.
    pub async fn post_rfqs(&self, body: &PostRfqsPayload) -> Result<PostRfqs200Response, Error> {
        let path = "/rfqs".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `DELETE /rfqs/{block_id}` — DELETE /rfqs/{block_id}
    /// Close an RFQ block
    pub async fn delete_rfqs_block_id(&self, block_id: &str) -> Result<DeleteRfqsBlockId200Response, Error> {
        let path = format!("/rfqs/{}", block_id);
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::DELETE, &path, query, None::<&()>, true).await
    }

    /// `GET /rfqs/{block_id}/quotes` — GET /rfqs/{block_id}/quotes
    /// Get the quotes for a given RFQ block.
    pub async fn get_rfqs_block_id_quotes(&self, block_id: &str) -> Result<GetRfqsBlockIdQuotes200Response, Error> {
        let path = format!("/rfqs/{}/quotes", block_id);
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /settlement-history` — GET /settlement-history
    /// Returns the historical settlement prices for a given asset.
    pub async fn get_settlement_history(&self, asset: Option<String>, start_time: Option<i64>, end_time: Option<i64>, limit: Option<i64>) -> Result<Vec<GetSettlementHistory200Response>, Error> {
        let path = "/settlement-history".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = asset {
            query_vec.push(("asset", v.to_string()));
        }
        if let Some(v) = start_time {
            query_vec.push(("start_time", v.to_string()));
        }
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `DELETE /signing-key` — DELETE /signing-key
    /// Removes the account's signing key. This logs out the account.
    pub async fn delete_signing_key(&self, body: &DeleteSigningKeyPayload) -> Result<DeleteSigningKey200Response, Error> {
        let path = "/signing-key".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::DELETE, &path, query, Some(body), true).await
    }

    /// `GET /stake` — GET /stake
    /// Returns the account's weekly trading volume, multiplier tier, stake history, LP NFT history, and top
    /// staker APR.
    pub async fn get_stake(&self) -> Result<GetStake200Response, Error> {
        let path = "/stake".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /statistics` — GET /statistics
    /// Returns the market statistics for the given asset.
    pub async fn get_statistics(&self, asset: Option<String>, instrument_type: Option<String>, end_time: Option<i64>) -> Result<GetStatistics200Response, Error> {
        let path = "/statistics".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = asset {
            query_vec.push(("asset", v.to_string()));
        }
        if let Some(v) = instrument_type {
            query_vec.push(("instrument_type", v.to_string()));
        }
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /strategies` — GET /strategies
    /// Returns the map of strategies.
    pub async fn get_strategies(&self) -> Result<GetStrategies200Response, Error> {
        let path = "/strategies".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /strategies/account` — GET /strategies/account
    /// Returns the account's strategy positions
    pub async fn get_strategies_account(&self) -> Result<GetStrategiesAccount200Response, Error> {
        let path = "/strategies/account".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /strategies/account-history` — GET /strategies/account-history
    /// Returns the account's strategy equity history
    pub async fn get_strategies_account_history(&self, start_time: i64, end_time: Option<i64>, resolution: Option<i64>) -> Result<GetStrategiesAccountHistory200Response, Error> {
        let path = "/strategies/account-history".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("start_time", start_time.to_string()));
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = resolution {
            query_vec.push(("resolution", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /strategy/{strategy_address}/balance-history` — GET
    /// /strategy/{strategy_address}/balance-history
    /// Return the strategy's balance history.
    pub async fn get_strategy_strategy_address_balance_history(&self, strategy_address: &str, start_time: i64, end_time: Option<i64>, resolution: Option<i64>) -> Result<GetStrategyStrategyAddressBalanceHistory200Response, Error> {
        let path = format!("/strategy/{}/balance-history", strategy_address);
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("start_time", start_time.to_string()));
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = resolution {
            query_vec.push(("resolution", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /strategy/{strategy_address}/initiate-withdraw` — POST
    /// /strategy/{strategy_address}/initiate-withdraw
    /// Initiate a USDC withdraw from strategy.
    pub async fn post_strategy_strategy_address_initiate_withdraw(&self, strategy_address: &str, body: &PostStrategyStrategyAddressInitiateWithdrawPayload) -> Result<PostStrategyStrategyAddressInitiateWithdraw200Response, Error> {
        let path = format!("/strategy/{}/initiate-withdraw", strategy_address);
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `GET /strategy/{strategy_address}/pnl-history` — GET /strategy/{strategy_address}/pnl-history
    /// Return the strategy's pnl history.
    pub async fn get_strategy_strategy_address_pnl_history(&self, strategy_address: &str, start_time: i64, end_time: Option<i64>, resolution: Option<i64>) -> Result<GetStrategyStrategyAddressPnlHistory200Response, Error> {
        let path = format!("/strategy/{}/pnl-history", strategy_address);
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("start_time", start_time.to_string()));
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = resolution {
            query_vec.push(("resolution", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /strategy/{strategy_address}/portfolio` — GET /strategy/{strategy_address}/portfolio
    /// Returns the overall portfolio details of the strategy
    pub async fn get_strategy_strategy_address_portfolio(&self, strategy_address: &str) -> Result<GetStrategyStrategyAddressPortfolio200Response, Error> {
        let path = format!("/strategy/{}/portfolio", strategy_address);
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /strategy/{strategy_address}/positions` — GET /strategy/{strategy_address}/positions
    /// Returns the strategy positions
    pub async fn get_strategy_strategy_address_positions(&self, strategy_address: &str) -> Result<GetStrategyStrategyAddressPositions200Response, Error> {
        let path = format!("/strategy/{}/positions", strategy_address);
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /strategy/{strategy_address}/trade-history` — GET /strategy/{strategy_address}/trade-history
    /// Return the account's trade history.
    pub async fn get_strategy_strategy_address_trade_history(&self, strategy_address: &str, start_time: i64, asset: Option<String>, end_time: Option<i64>, trade_types: Option<String>, instrument_type: Option<String>, option_type: Option<String>, limit: Option<i64>, offset: Option<i64>) -> Result<GetStrategyStrategyAddressTradeHistory200Response, Error> {
        let path = format!("/strategy/{}/trade-history", strategy_address);
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("start_time", start_time.to_string()));
        if let Some(v) = asset {
            query_vec.push(("asset", v.to_string()));
        }
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = trade_types {
            query_vec.push(("trade_types", v.to_string()));
        }
        if let Some(v) = instrument_type {
            query_vec.push(("instrument_type", v.to_string()));
        }
        if let Some(v) = option_type {
            query_vec.push(("option_type", v.to_string()));
        }
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        if let Some(v) = offset {
            query_vec.push(("offset", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /strategy/{strategy_address}/transaction-history` — GET
    /// /strategy/{strategy_address}/transaction-history
    /// Return the strategy's deposit and withdraw history.
    pub async fn get_strategy_strategy_address_transaction_history(&self, strategy_address: &str, start_time: Option<i64>, end_time: Option<i64>, tx_type: Option<String>, tx_status: Option<String>, limit: Option<i64>, offset: Option<i64>) -> Result<GetStrategyStrategyAddressTransactionHistory200Response, Error> {
        let path = format!("/strategy/{}/transaction-history", strategy_address);
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = start_time {
            query_vec.push(("start_time", v.to_string()));
        }
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = tx_type {
            query_vec.push(("tx_type", v.to_string()));
        }
        if let Some(v) = tx_status {
            query_vec.push(("tx_status", v.to_string()));
        }
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        if let Some(v) = offset {
            query_vec.push(("offset", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /swap` — POST /swap
    /// Swaps collateral.
    pub async fn post_swap(&self, body: &PostSwapPayload) -> Result<PostSwap200Response, Error> {
        let path = "/swap".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `POST /swap/preview` — POST /swap/preview
    /// Previews a collateral swap
    pub async fn post_swap_preview(&self, body: &PostSwapPreviewPayload) -> Result<PostSwapPreview200Response, Error> {
        let path = "/swap/preview".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `GET /time` — GET /time
    /// Returns the server time
    pub async fn get_time(&self) -> Result<GetTime200Response, Error> {
        let path = "/time".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `GET /trade-fees-campaign-stats` — GET /trade-fees-campaign-stats
    /// Return the account's trading fee statistics.
    pub async fn get_trade_fees_campaign_stats(&self) -> Result<GetTradeFeesCampaignStats200Response, Error> {
        let path = "/trade-fees-campaign-stats".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /trade-history` — GET /trade-history
    /// Return the account's trade history.
    pub async fn get_trade_history(&self, start_time: i64, asset: Option<String>, end_time: Option<i64>, trade_types: Option<String>, instrument_type: Option<String>, option_type: Option<String>, limit: Option<i64>, offset: Option<i64>) -> Result<GetTradeHistory200Response, Error> {
        let path = "/trade-history".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        query_vec.push(("start_time", start_time.to_string()));
        if let Some(v) = asset {
            query_vec.push(("asset", v.to_string()));
        }
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = trade_types {
            query_vec.push(("trade_types", v.to_string()));
        }
        if let Some(v) = instrument_type {
            query_vec.push(("instrument_type", v.to_string()));
        }
        if let Some(v) = option_type {
            query_vec.push(("option_type", v.to_string()));
        }
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        if let Some(v) = offset {
            query_vec.push(("offset", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /transaction-history` — GET /transaction-history
    /// Return the account's deposit and withdraw history.
    pub async fn get_transaction_history(&self, start_time: Option<i64>, end_time: Option<i64>, tx_type: Option<String>, tx_status: Option<String>, limit: Option<i64>, offset: Option<i64>) -> Result<GetTransactionHistory200Response, Error> {
        let path = "/transaction-history".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = start_time {
            query_vec.push(("start_time", v.to_string()));
        }
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = tx_type {
            query_vec.push(("tx_type", v.to_string()));
        }
        if let Some(v) = tx_status {
            query_vec.push(("tx_status", v.to_string()));
        }
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        if let Some(v) = offset {
            query_vec.push(("offset", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /transfer` — POST /transfer
    /// Transfer USDC between accounts.
    pub async fn post_transfer(&self, body: &PostTransferPayload) -> Result<PostTransfer200Response, Error> {
        let path = "/transfer".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `GET /twap-order-history` — GET /twap-order-history
    /// Returns TWAP child order execution history for the account.
    pub async fn get_twap_order_history(&self, start_time: Option<i64>, end_time: Option<i64>, limit: Option<i64>, offset: Option<i64>) -> Result<GetTwapOrderHistory200Response, Error> {
        let path = "/twap-order-history".to_string();
        let mut query_vec: Vec<(&str, String)> = Vec::new();
        if let Some(v) = start_time {
            query_vec.push(("start_time", v.to_string()));
        }
        if let Some(v) = end_time {
            query_vec.push(("end_time", v.to_string()));
        }
        if let Some(v) = limit {
            query_vec.push(("limit", v.to_string()));
        }
        if let Some(v) = offset {
            query_vec.push(("offset", v.to_string()));
        }
        let query = Some(query_vec.as_slice());
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /twap-orders` — GET /twap-orders
    /// Returns all active TWAP orders for the account.
    pub async fn get_twap_orders(&self) -> Result<GetTwapOrders200Response, Error> {
        let path = "/twap-orders".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `POST /twap-orders` — POST /twap-orders
    /// Creates a new TWAP (Time-Weighted Average Price) order.
    pub async fn post_twap_orders(&self, body: &PostTwapOrdersPayload) -> Result<PostTwapOrders200Response, Error> {
        let path = "/twap-orders".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), true).await
    }

    /// `DELETE /twap-orders/{order_id}` — DELETE /twap-orders/{order_id}
    /// Cancels a TWAP order.
    pub async fn delete_twap_orders_order_id(&self, order_id: &str) -> Result<DeleteTwapOrdersOrderId200Response, Error> {
        let path = format!("/twap-orders/{}", order_id);
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::DELETE, &path, query, None::<&()>, true).await
    }

    /// `GET /twap-orders/{order_id}` — GET /twap-orders/{order_id}
    /// Returns a specific TWAP order by ID.
    pub async fn get_twap_orders_order_id(&self, order_id: &str) -> Result<GetTwapOrdersOrderId200Response, Error> {
        let path = format!("/twap-orders/{}", order_id);
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, true).await
    }

    /// `GET /weeth` — GET /weeth
    /// Returns the total weETH deposits.
    pub async fn get_weeth(&self) -> Result<GetWeeth200Response, Error> {
        let path = "/weeth".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

    /// `POST /withdraw` — POST /withdraw
    /// Withdraws USDC from the exchange to L1 Ethereum.
    pub async fn post_withdraw(&self, body: &PostWithdrawPayload) -> Result<PostWithdraw200Response, Error> {
        let path = "/withdraw".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::POST, &path, query, Some(body), false).await
    }

    /// `GET /yield-vault` — GET /yield-vault
    /// Returns the yield vault information for the given yield vault.
    pub async fn get_yield_vault(&self) -> Result<GetYieldVault200Response, Error> {
        let path = "/yield-vault".to_string();
        let query: Option<&[(&str, String)]> = None;
        self.send(reqwest::Method::GET, &path, query, None::<&()>, false).await
    }

}
